#! /bin/sh

sxhkd &
compton &
nitrogen --restore &
$HOME/.screenlayout/double.sh
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &

bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         	1
bspc config window_gap           	10

#bspc config focused_border_color 	"#e8ecb2"
bspc config focused_border_color 	"#4bffdc"
bspc config focus_follows_pointer	true

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
